spring:  
  profiles:  
    active: dev  
spring:  
  profiles: dev  
  datasource:  
    url: jdbc:mysql://localhost:3306/devdb  
    username: devuser  
    password: devpass  
spring:  
  profiles: prod  
  datasource:  
    url: jdbc:mysql://localhost:3306/proddb  
    username: produser  
    password: prodpass 